// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingApp.Data.Context;

#nullable disable

namespace WeddingApp.Migrations
{
    [DbContext(typeof(WeddingAppUserContext))]
    partial class WeddingAppUserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WeddingApp.Data.Entities.PictureEntity", b =>
                {
                    b.Property<string>("PicturePath")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserEntityUserID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PicturePath");

                    b.HasIndex("UserEntityUserID");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("WeddingApp.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserID");

                    b.HasIndex("UserPhone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WeddingApp.Data.Entities.PictureEntity", b =>
                {
                    b.HasOne("WeddingApp.Data.Entities.UserEntity", null)
                        .WithMany("Posts")
                        .HasForeignKey("UserEntityUserID");
                });

            modelBuilder.Entity("WeddingApp.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
