name: Build and test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
    runs-on: windows-latest
    env:
      Solution_Name: WeddingApp/WeddingApp.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Project_Name: WeddingApp/WeddingApp.csproj
      Test_Project_Path: TestsLibrary.Tests/TestsLibrary.Tests.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
    - name: Execute backend unit tests
      env:
        ConnectionStringClass:mainpc : ${{ secrets.MAINPC }}
      run: dotnet test --filter "FullyQualifiedName=TestsLibrary.Backend"
      working-directory: TestsLibrary

    - name: Publish
      run: msbuild $env:Project_Name /p:DeployOnBuild=true /p:PublishProfile=WeddingApp\Properties\PublishProfiles\IISProfile1.pubxml /p:Password=${{ secrets.PASSWORD }} /p:AllowUntrustedCertificate=true

    - name: Execute frontend unit tests
      env:
        ConnectionStringClass:mainpc : ${{ secrets.MAINPC }}
      run: dotnet test --filter "FullyQualifiedName=TestsLibrary.Frontend"
      working-directory: TestsLibrary